config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  root 'static_pages#home'

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'
  # get 'static_pages/contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'application#hello'
  resources :users
  resources :microposts,    only: [:create, :destroy, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  attr_accessor :remember_token
  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Return the hash digest of a given string
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(self.remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(remember_token)
    # if self.remember_digest.nil? 
    #   return false 
    # end
    return false if self.remember_digest.nil?
    BCrypt::Password.new(self.remember_digest).is_password?(remember_token)
  end

  def feed
    Micropost.where("user_id = ?", id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :index, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index 
    @users = User.paginate(page: params[:page])
    #@users = User.all
    #print("INSPECTING RESULT: #{@users.class}")
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      # render 'show'
      # if we use render 'show' here, the view would be show.html.erb
      # but looking at the url, it is still /signup. This one makes sense as we look at the routes
      # POST   /signup(.:format)         users#create
      # we actually did not do anything to change the URL
      flash[:success] = "Welcome to the Sample App!"
      redirect_to user_url(@user)
    else 
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile  updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:url)) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %> 

  <%= f.submit yield(:button_value), class: "btn btn-primary" %>       
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? and !current_user?(user) %>
    | <%= link_to "delete", user_path(user), method: :delete, 
                                           data: {confirm: "You sure?"} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<%# provide(:title, 'Edit user') %>
<!-- <h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%#= form_for(@user, url: user_path, method: :patch) do |f| %>
      <%#= render 'shared/error_messages' %>
      <%#= f.label :name %>
      <%#= f.text_field :name, class: 'form-control' %>

      <%#= f.label :email %>
      <%#= f.email_field :email, class: 'form-control' %>

      <%#= f.label :password %>
      <%#= f.password_field :password, class: 'form-control' %>

      <%#= f.label :password_confirmation, "Confirmation" %>
      <%#= f.password_field :password_confirmation, class: 'form-control' %> 

      <%#= f.submit "Save changes", class: "btn btn-primary" %>       
    <%# end %>
    
    <div class="gravatar_edit">
      <%#= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
    </div>
  </div>
</div> -->

<% provide(:title, 'Edit user') %>
<% provide(:url, user_path) %>
<% provide(:button_value, "Save changes") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'users/form' %>
    
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">Change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All users") %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<%# provide(:title, 'Sign up') %>
<!-- <h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%#= form_for(@user, url: signup_path) do |f| %>
      <%#= render 'shared/error_messages' %>
      <%#= f.label :name %>
      <%#= f.text_field :name, class: 'form-control' %>

      <%#= f.label :email %>
      <%#= f.email_field :email, class: 'form-control' %>

      <%#= f.label :password %>
      <%#= f.password_field :password, class: 'form-control' %>

      <%#= f.label :password_confirmation, "Confirmation" %>
      <%#= f.password_field :password_confirmation, class: 'form-control' %> 

      <%#= f.submit "Create my account", class: "btn btn-primary" %>       
    <%# end %>
  </div>
</div> -->

<% provide(:title, 'Sign up') %>
<% provide(:url, signup_path) %>
<% provide(:button_value, "Create my account") %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'users/form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user, size: 120 %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>